import Head from 'next/head'
import { Input } from '@geist-ui/core'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Mordor Faucet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Ethereum Classic Mordor Faucet
          </p>
        </div>

        <div className={styles.center}>
          <Input crossOrigin={'undefined'} placeholder="email@address" value={''} width={20} />
        </div>

        <div className={styles.grid}>
        </div>
      </main>
    </>
  )
}
